fix(sql): added auto-database create
esx-framework/esx-legacy pull request #110
Opened 2022-02-18 12:47 UTC by konijn-x

Creates an database automatic.

2022-02-18 14:17 UTC, PsychoShock requested changes

2022-02-18 14:17 UTC, PsychoShock commented on [SQL]/legacy.sql
> +USE `esx-legacy`;
USE `esx_legacy`;


Fix typo :D

2022-02-18 16:14 UTC, 0xDEMXN approved these changes

2022-02-21 17:39 UTC, Mycroft-Studios commented
This *may* Break the TxAdmin recipe

2022-02-21 17:51 UTC, Esplike commented
I'll have a look into it because I don't want to break the recipe...

2022-02-23 23:29 UTC, Esplike commented
This would break the repipe for ESX because TXAdmin automatically creates the database.

2022-02-23 23:29 UTC, closed without merging