Refactor event
esx-framework/esx-legacy pull request #165
Opened 2022-03-19 06:05 UTC by MonsterTaerAttO

2022-03-27 05:44 UTC, TheLazarusRising commented
Please use proper commit messages:

https://www.conventionalcommits.org/en/v1.0.0/

I should know what you've done without having to look at the code.

2022-04-07 14:50 UTC, PsychoShock commented on [esx_addons]/esx_ambulancejob/fxmanifest.lua
> -shared_scripts {
huh? Why would you make a change like that...

2022-04-07 14:52 UTC, PsychoShock commented on [esx_addons]/esx_lscustom/client/main.lua
> +		if lsMenuIsShowed then
also why? Set a function and only call it when needed.

2022-04-07 14:53 UTC, PsychoShock commented on [esx_addons]/esx_mechanicjob/client/main.lua
> +			end
Code like this it's just wrong... please don't use that. Only change the value when needed.

2022-04-07 14:54 UTC, PsychoShock requested changes

2022-04-08 14:56 UTC, closed without merging