refactor(esx_society/client/main.lua) : Fixed stuff in boss menu and added translations
esx-framework/esx-legacy pull request #575
Opened 2022-10-17 09:50 UTC by lexinor

- Added a possibility to return from almost every part in the boss menu, that's why we are now passing "options" through the whole menu to be able to come back at the initial state.

- Added a null check when changing a job grade's name by "nil" and did the same for job ranks.

- Added some new translations. I only translated FR and EN, others are just plain english values

2022-11-07 20:47 UTC, bitpredator requested changes
I have corrected the new translations inserted regarding the Italian language

2022-11-07 20:47 UTC, bitpredator commented on [esx_addons]/esx_society/locales/it.lua
> +  ['invalid_value']          = 'invalid value',
['invalid_value']  = 'valore non valido',

2022-11-07 20:47 UTC, bitpredator commented on [esx_addons]/esx_society/locales/it.lua
> +  ['invalid_value_nochanges']= 'invalid value, no changes applied',
['invalid_value_nochanges']= 'valore non valido, nessuna modifica applicata',

2022-11-07 20:55 UTC, bitpredator requested changes

2022-11-07 20:55 UTC, bitpredator commented on [esx_addons]/esx_society/locales/it.lua
> +  ['invalid_value']          = 'invalid value',
```suggestion
  ['invalid_value']          = 'valore non valido',  
```

2022-11-07 20:55 UTC, bitpredator commented on [esx_addons]/esx_society/locales/it.lua
> +  ['invalid_value_nochanges']= 'invalid value, no changes applied',
```suggestion
  ['invalid_value_nochanges']= 'valore non valido, nessuna modifica applicata',
```

2022-11-07 21:11 UTC, lexinor commented on [esx_addons]/esx_society/locales/it.lua
> +  ['invalid_value']          = 'invalid value',
Thanks for your participation !

2022-11-07 21:13 UTC, lexinor reviewed
Include that translation

2022-11-14 17:54 UTC, lexinor commented
@Benzo00 Any news ?

2022-11-16 10:26 UTC, lexinor commented
@JackDUpModZ @Benzo00 Could you review it please ? I need it merged

2022-11-17 20:06 UTC, TrymTube approved these changes

2022-11-17 21:35 UTC, bitpredator approved these changes

2022-11-27 00:01 UTC, Gellipapa commented
@lexinor Thank you for pull request.  Sorry for the long wait, there will soon be changes in the acceptance of PRs. I tested it and there are no bugs in it but I rewrote two things on the server side. Soon to be merged.

2022-11-27 01:10 UTC, Gellipapa approved these changes
Tested, works.

2022-11-27 01:10 UTC, merged

2022-11-27 08:01 UTC, lexinor commented
> @lexinor Thank you for pull request.  Sorry for the long wait, there will soon be changes in the acceptance of PRs. I tested it and there are no bugs in it but I rewrote two things on the server side. Soon to be merged. 

Thanks for your response, I hope it will be faster next time 😅😅.
There are still some work to do on the menu anyway so glad to see that

2022-11-27 15:11 UTC, Gellipapa commented
Yes, for exampl outsource all burned-in menu text to a local file.