refactor(es_extended):⚠️hardcap ditch
esx-framework/esx-legacy pull request #613
Opened 2022-11-01 17:44 UTC by Tinky124

No more using hardcap...

2022-11-01 18:04 UTC, Tinky124 reviewed
Can somebody look this?

2022-11-02 19:50 UTC, Mycroft-Studios requested changes
Overall, this PR makes 0 sense and has many issues

2022-11-02 19:50 UTC, Mycroft-Studios commented on [esx]/es_extended/client/main.lua
> +	'mysql-async',
cannot Add , since oxmysql provides for mysql-async, causing a false positive

2022-11-02 19:50 UTC, Mycroft-Studios commented on [esx]/es_extended/server/main.lua
> +local cv = GetConvarInt('sv_maxclients', 32)
should be 48, not 32

2022-11-02 19:50 UTC, Mycroft-Studios commented on [esx]/es_extended/client/main.lua
> +  	RequestIpl("CS1_02_cf_offmission")
why????
Literally no need to turn ESX into a IPL loader that u cant even disable

2022-11-03 16:11 UTC, Tinky124 commented
Since this community is toxic i dont care anymore for esx, and i dont want to use it anymore qbus is better.

2022-11-03 16:11 UTC, closed without merging

2022-11-03 18:47 UTC, Mycroft-Studios commented
man makes a PR that makes 0 sense and then calls us toxic for questioning it, amazing :)