Add Config.BossGrades
esx-framework/esx-legacy pull request #732
Opened 2022-12-05 14:27 UTC by Lunar-Scripts

Added the option to allow other grades than 'boss' to access the boss menu.
Could for example be used to allow an player with an 'underboss' grade to access the boss menu.

2022-12-08 05:05 UTC, Taavi-AU approved these changes

2022-12-09 07:57 UTC, wobozkyng commented
this will need more adjustment for other resources, e.g. esx_policejob has client control for job grades to access boss menu.

2022-12-15 18:51 UTC, CsokiHUN requested changes

2022-12-15 18:51 UTC, CsokiHUN commented on [esx_addons]/esx_society/config.lua
> +}
```suggestion
Config.BossGrades = {
  ['boss'] = true
}
```

2022-12-15 18:51 UTC, CsokiHUN commented on [esx_addons]/esx_society/server/main.lua
> +end
```suggestion
function IsGradeBoss(grade)
  return Config.BossGrades[grade]
end
```

2022-12-15 18:52 UTC, CsokiHUN commented
unnecessary for loop, please change to my solution

2022-12-15 19:32 UTC, xorzo1 approved these changes

2022-12-19 16:51 UTC, Benzo00 commented
Closed due to changes not being added, also will break other resources. please reach out when changes are made and i will reopen this

2022-12-19 16:51 UTC, closed without merging