Create fr.lua
esx-framework/esx-legacy pull request #800
Opened 2023-01-02 18:29 UTC by PitaAuPoulet

Translation for French people

2023-01-02 20:24 UTC, TheFantomas approved these changes

2023-01-03 18:20 UTC, jbdevic requested changes

2023-01-03 18:20 UTC, jbdevic commented on [esx]/esx_identity/locales/fr.lua
> +    ['invalid_firstname_format'] = 'Format invalide (First Name): Veuillez réessayer.',
First Name --> Prénom

2023-01-03 18:20 UTC, jbdevic commented on [esx]/esx_identity/locales/fr.lua
> +    ['invalid_lastname_format'] = 'Format invalide (Last Name): Veuillez réessayer.',
Nom de famille

2023-01-03 18:20 UTC, jbdevic commented on [esx]/esx_identity/locales/fr.lua
> +    ['invalid_dob_format'] = 'Format invalide (DOB): Veuillez réessayer.',
Date de naissance

2023-01-03 18:20 UTC, jbdevic commented on [esx]/esx_identity/locales/fr.lua
> +    ['invalid_sex_format'] = 'Format invalide (Sex): Veuillez réessayer.',
Sexe

2023-01-03 18:20 UTC, jbdevic commented on [esx]/esx_identity/locales/fr.lua
> +    ['invalid_height_format'] = 'Format invalide (Height): Veuillez réessayer.'
Poids

2023-01-03 18:20 UTC, jbdevic commented on [esx]/esx_identity/locales/fr.lua
> +    ['return_debug_xPlayer_get_height'] = 'Taille: %s Inches',
Inches --> centimètres

2023-01-03 18:20 UTC, jbdevic commented on [esx]/esx_identity/locales/fr.lua
> +    ['error_debug_xPlayer_get_height'] = 'Il y avait un problème lors de l’obtention de votre taille.',
Il y a eu

2023-01-03 18:20 UTC, jbdevic commented on [esx]/esx_identity/locales/fr.lua
> +    ['error_debug_xPlayer_get_sex'] = 'Il y avait un problème en obtenant votre sexe.',
Il y a eu

2023-01-09 15:20 UTC, TheFantomas commented
@jbdevic Can you create a pr? The gentleman probably won't be very active, so don't get stuck here :D

2023-01-09 15:34 UTC, PitaAuPoulet commented
Sorry, first time i do that, do i have to do something more?

2023-01-09 18:43 UTC, jbdevic commented
> Sorry, first time i do that, do i have to do something more?

You need to fix the comment of my review

2023-01-18 12:52 UTC, Benzo00 commented
No respond after 2 weeks.

2023-01-18 12:52 UTC, closed without merging